window.esdocSearchIndex = [
  [
    "@schibstedspain/zeus-api-generator/src/parser/htmlparser.js~htmlparser",
    "class/src/parser/htmlParser.js~HtmlParser.html",
    "<span>HtmlParser</span> <span class=\"search-result-import-path\">@schibstedspain/zeus-api-generator/src/parser/htmlParser.js</span>",
    "class"
  ],
  [
    "@schibstedspain/zeus-api-generator/src/url/index.js~no_base_path",
    "variable/index.html#static-variable-NO_BASE_PATH",
    "<span>NO_BASE_PATH</span> <span class=\"search-result-import-path\">@schibstedspain/zeus-api-generator/src/url/index.js</span>",
    "variable"
  ],
  [
    "@schibstedspain/zeus-api-generator/src/url/index.js~no_host",
    "variable/index.html#static-variable-NO_HOST",
    "<span>NO_HOST</span> <span class=\"search-result-import-path\">@schibstedspain/zeus-api-generator/src/url/index.js</span>",
    "variable"
  ],
  [
    "@schibstedspain/zeus-api-generator/src/url/index.js~no_path",
    "variable/index.html#static-variable-NO_PATH",
    "<span>NO_PATH</span> <span class=\"search-result-import-path\">@schibstedspain/zeus-api-generator/src/url/index.js</span>",
    "variable"
  ],
  [
    "@schibstedspain/zeus-api-generator/src/parser/parser.js~parser",
    "class/src/parser/parser.js~Parser.html",
    "<span>Parser</span> <span class=\"search-result-import-path\">@schibstedspain/zeus-api-generator/src/parser/parser.js</span>",
    "class"
  ],
  [
    "@schibstedspain/zeus-api-generator/src/sections/section.js~section",
    "class/src/sections/section.js~Section.html",
    "<span>Section</span> <span class=\"search-result-import-path\">@schibstedspain/zeus-api-generator/src/sections/section.js</span>",
    "class"
  ],
  [
    "@schibstedspain/zeus-api-generator/src/sections/factory.js~sectionsfactory",
    "class/src/sections/factory.js~SectionsFactory.html",
    "<span>SectionsFactory</span> <span class=\"search-result-import-path\">@schibstedspain/zeus-api-generator/src/sections/factory.js</span>",
    "class"
  ],
  [
    "@schibstedspain/zeus-api-generator/src/url/index.js~url",
    "class/src/url/index.js~Url.html",
    "<span>Url</span> <span class=\"search-result-import-path\">@schibstedspain/zeus-api-generator/src/url/index.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/parser/htmlParserSpec.js.html#lineNumber14",
    "HtmlParser",
    "test"
  ],
  [
    "",
    "test-file/test/parser/htmlParserSpec.js.html#lineNumber19",
    "HtmlParser An instance with a empty html param",
    "test"
  ],
  [
    "",
    "test-file/test/parser/htmlParserSpec.js.html#lineNumber20",
    "HtmlParser An instance with a empty html param expect throw an exception",
    "test"
  ],
  [
    "",
    "test-file/test/parser/htmlParserSpec.js.html#lineNumber25",
    "HtmlParser An instance with a valid HTML string",
    "test"
  ],
  [
    "",
    "test-file/test/parser/htmlParserSpec.js.html#lineNumber43",
    "HtmlParser An instance with a valid HTML string expect be possible query for the description attribute",
    "test"
  ],
  [
    "",
    "test-file/test/parser/htmlParserSpec.js.html#lineNumber35",
    "HtmlParser An instance with a valid HTML string expect be possible query for the name attribute",
    "test"
  ],
  [
    "",
    "test-file/test/parser/htmlParserSpec.js.html#lineNumber39",
    "HtmlParser An instance with a valid HTML string expect be possible query for the title attribute",
    "test"
  ],
  [
    "",
    "test-file/test/parser/htmlParserSpec.js.html#lineNumber15",
    "HtmlParser Expect be an instanciable class",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber9",
    "Section",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber14",
    "Section .build",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber21",
    "Section .build Given a path for a static page",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber51",
    "Section .build Given a path for a static page expect have a describe in the section",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber43",
    "Section .build Given a path for a static page expect have a name in the section",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber47",
    "Section .build Given a path for a static page expect have a title in the section",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber55",
    "Section .build Given a path for a static page expect have a url attribute with the dirrection for the static page",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber37",
    "Section .build Given a path for a static page expect return a promise with the an instance created",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber15",
    "Section .build Given an empty path",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber16",
    "Section .build Given an empty path expect throw an error",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionSpec.js.html#lineNumber10",
    "Section expect be an instanciable class",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionsFactorySpec.js.html#lineNumber10",
    "SectionsFactory",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionsFactorySpec.js.html#lineNumber12",
    "SectionsFactory Expect be an instanciable class",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionsFactorySpec.js.html#lineNumber24",
    "SectionsFactory Given a path",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionsFactorySpec.js.html#lineNumber34",
    "SectionsFactory Given a path expect return a list of Section Objects when call #sections method",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionsFactorySpec.js.html#lineNumber16",
    "SectionsFactory Given an empty path",
    "test"
  ],
  [
    "",
    "test-file/test/sections/sectionsFactorySpec.js.html#lineNumber18",
    "SectionsFactory Given an empty path expect throw an error",
    "test"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/parser/htmlparser.js",
    "file/src/parser/htmlParser.js.html",
    "src/parser/htmlParser.js",
    "file"
  ],
  [
    "src/parser/htmlparser.js~htmlparser#$",
    "class/src/parser/htmlParser.js~HtmlParser.html#instance-member-$",
    "src/parser/htmlParser.js~HtmlParser#$",
    "member"
  ],
  [
    "src/parser/htmlparser.js~htmlparser#constructor",
    "class/src/parser/htmlParser.js~HtmlParser.html#instance-constructor-constructor",
    "src/parser/htmlParser.js~HtmlParser#constructor",
    "method"
  ],
  [
    "src/parser/htmlparser.js~htmlparser#description",
    "class/src/parser/htmlParser.js~HtmlParser.html#instance-get-description",
    "src/parser/htmlParser.js~HtmlParser#description",
    "member"
  ],
  [
    "src/parser/htmlparser.js~htmlparser#name",
    "class/src/parser/htmlParser.js~HtmlParser.html#instance-get-name",
    "src/parser/htmlParser.js~HtmlParser#name",
    "member"
  ],
  [
    "src/parser/htmlparser.js~htmlparser#title",
    "class/src/parser/htmlParser.js~HtmlParser.html#instance-get-title",
    "src/parser/htmlParser.js~HtmlParser#title",
    "member"
  ],
  [
    "src/parser/index.js",
    "file/src/parser/index.js.html",
    "src/parser/index.js",
    "file"
  ],
  [
    "src/parser/parser.js",
    "file/src/parser/parser.js.html",
    "src/parser/parser.js",
    "file"
  ],
  [
    "src/parser/parser.js~parser#description",
    "class/src/parser/parser.js~Parser.html#instance-get-description",
    "src/parser/parser.js~Parser#description",
    "member"
  ],
  [
    "src/parser/parser.js~parser#name",
    "class/src/parser/parser.js~Parser.html#instance-get-name",
    "src/parser/parser.js~Parser#name",
    "member"
  ],
  [
    "src/parser/parser.js~parser#title",
    "class/src/parser/parser.js~Parser.html#instance-get-title",
    "src/parser/parser.js~Parser#title",
    "member"
  ],
  [
    "src/sections/factory.js",
    "file/src/sections/factory.js.html",
    "src/sections/factory.js",
    "file"
  ],
  [
    "src/sections/factory.js~sectionsfactory#constructor",
    "class/src/sections/factory.js~SectionsFactory.html#instance-constructor-constructor",
    "src/sections/factory.js~SectionsFactory#constructor",
    "method"
  ],
  [
    "src/sections/factory.js~sectionsfactory#path",
    "class/src/sections/factory.js~SectionsFactory.html#instance-member-path",
    "src/sections/factory.js~SectionsFactory#path",
    "member"
  ],
  [
    "src/sections/factory.js~sectionsfactory#sections",
    "class/src/sections/factory.js~SectionsFactory.html#instance-method-sections",
    "src/sections/factory.js~SectionsFactory#sections",
    "method"
  ],
  [
    "src/sections/index.js",
    "file/src/sections/index.js.html",
    "src/sections/index.js",
    "file"
  ],
  [
    "src/sections/section.js",
    "file/src/sections/section.js.html",
    "src/sections/section.js",
    "file"
  ],
  [
    "src/sections/section.js~section#constructor",
    "class/src/sections/section.js~Section.html#instance-constructor-constructor",
    "src/sections/section.js~Section#constructor",
    "method"
  ],
  [
    "src/sections/section.js~section#description",
    "class/src/sections/section.js~Section.html#instance-get-description",
    "src/sections/section.js~Section#description",
    "member"
  ],
  [
    "src/sections/section.js~section#name",
    "class/src/sections/section.js~Section.html#instance-get-name",
    "src/sections/section.js~Section#name",
    "member"
  ],
  [
    "src/sections/section.js~section#parser",
    "class/src/sections/section.js~Section.html#instance-member-parser",
    "src/sections/section.js~Section#parser",
    "member"
  ],
  [
    "src/sections/section.js~section#title",
    "class/src/sections/section.js~Section.html#instance-get-title",
    "src/sections/section.js~Section#title",
    "member"
  ],
  [
    "src/sections/section.js~section.build",
    "class/src/sections/section.js~Section.html#static-method-build",
    "src/sections/section.js~Section.build",
    "method"
  ],
  [
    "src/url/index.js",
    "file/src/url/index.js.html",
    "src/url/index.js",
    "file"
  ],
  [
    "src/url/index.js~url#absolute",
    "class/src/url/index.js~Url.html#instance-method-absolute",
    "src/url/index.js~Url#absolute",
    "method"
  ],
  [
    "src/url/index.js~url#basepath",
    "class/src/url/index.js~Url.html#instance-set-basePath",
    "src/url/index.js~Url#basePath",
    "member"
  ],
  [
    "src/url/index.js~url#constructor",
    "class/src/url/index.js~Url.html#instance-constructor-constructor",
    "src/url/index.js~Url#constructor",
    "method"
  ],
  [
    "src/url/index.js~url#host",
    "class/src/url/index.js~Url.html#instance-set-host",
    "src/url/index.js~Url#host",
    "member"
  ],
  [
    "test/parser/htmlparserspec.js",
    "test-file/test/parser/htmlParserSpec.js.html",
    "test/parser/htmlParserSpec.js",
    "testFile"
  ],
  [
    "test/sections/sectionspec.js",
    "test-file/test/sections/sectionSpec.js.html",
    "test/sections/sectionSpec.js",
    "testFile"
  ],
  [
    "test/sections/sectionsfactoryspec.js",
    "test-file/test/sections/sectionsFactorySpec.js.html",
    "test/sections/sectionsFactorySpec.js",
    "testFile"
  ],
  [
    "test/url/urlspec.js",
    "test-file/test/url/urlSpec.js.html",
    "test/url/urlSpec.js",
    "testFile"
  ],
  [
    "",
    "test-file/test/url/urlSpec.js.html#lineNumber9",
    "url",
    "test"
  ],
  [
    "",
    "test-file/test/url/urlSpec.js.html#lineNumber18",
    "url Setting host and basePath",
    "test"
  ],
  [
    "",
    "test-file/test/url/urlSpec.js.html#lineNumber12",
    "url Whitout setting the host and basePath",
    "test"
  ],
  [
    "",
    "test-file/test/url/urlSpec.js.html#lineNumber13",
    "url Whitout setting the host and basePath Expect throw an error when request for the absolute URL",
    "test"
  ],
  [
    "",
    "test-file/test/url/urlSpec.js.html#lineNumber10",
    "url expect be an instance of Url",
    "test"
  ]
]